/* This file is generated by deploy.js automatically */
var Building = function Building(args) {
    this.pk = 'userId';
    this.column = ["userId","castleNextHarvestMoneyTime","castleHarvestBonus","cardNextRecruit1Time","cardDailyRecruit1Count","cardLastResetDailyRecruit1CountTime","cardNextRecruit2Time","cardNextRecruit3Time","cardNextRecruit4Time","barrackFormation1","barrackFormation2","barrackFormation3","barrackActiveFormationId"];
    this.abb = {"userId":"ui","castleNextHarvestMoneyTime":"cnhmt","castleHarvestBonus":"chb","cardNextRecruit1Time":"cnr1t","cardDailyRecruit1Count":"cdr1c","cardLastResetDailyRecruit1CountTime":"clrdr1ct","cardNextRecruit2Time":"cnr2t","cardNextRecruit3Time":"cnr3t","cardNextRecruit4Time":"cnr4t","barrackFormation1":"bf1","barrackFormation2":"bf2","barrackFormation3":"bf3","barrackActiveFormationId":"bafi"};
    this.init.call(this, args);
};

Building.prototype = new IObject();
Building.prototype.constructor = Building;

/* Getter */
Building.prototype.__defineGetter__('userId', function() { return this.args[0]; });
Building.prototype.__defineGetter__('castleNextHarvestMoneyTime', function() { return this.args[1]; });
Building.prototype.__defineGetter__('castleHarvestBonus', function() { return this.args[2]; });
Building.prototype.__defineGetter__('cardNextRecruit1Time', function() { return this.args[3]; });
Building.prototype.__defineGetter__('cardDailyRecruit1Count', function() { return this.args[4]; });
Building.prototype.__defineGetter__('cardLastResetDailyRecruit1CountTime', function() { return this.args[5]; });
Building.prototype.__defineGetter__('cardNextRecruit2Time', function() { return this.args[6]; });
Building.prototype.__defineGetter__('cardNextRecruit3Time', function() { return this.args[7]; });
Building.prototype.__defineGetter__('cardNextRecruit4Time', function() { return this.args[8]; });
Building.prototype.__defineGetter__('barrackFormation1', function() { return this.args[9]; });
Building.prototype.__defineGetter__('barrackFormation2', function() { return this.args[10]; });
Building.prototype.__defineGetter__('barrackFormation3', function() { return this.args[11]; });
Building.prototype.__defineGetter__('barrackActiveFormationId', function() { return this.args[12]; });

/* Setter */
Building.prototype.__defineSetter__('userId', function(val) { this.args[0] = val; this.updateList[0] = 1; });
Building.prototype.__defineSetter__('castleNextHarvestMoneyTime', function(val) { this.args[1] = val; this.updateList[1] = 1; });
Building.prototype.__defineSetter__('castleHarvestBonus', function(val) { this.args[2] = val; this.updateList[2] = 1; });
Building.prototype.__defineSetter__('cardNextRecruit1Time', function(val) { this.args[3] = val; this.updateList[3] = 1; });
Building.prototype.__defineSetter__('cardDailyRecruit1Count', function(val) { this.args[4] = val; this.updateList[4] = 1; });
Building.prototype.__defineSetter__('cardLastResetDailyRecruit1CountTime', function(val) { this.args[5] = val; this.updateList[5] = 1; });
Building.prototype.__defineSetter__('cardNextRecruit2Time', function(val) { this.args[6] = val; this.updateList[6] = 1; });
Building.prototype.__defineSetter__('cardNextRecruit3Time', function(val) { this.args[7] = val; this.updateList[7] = 1; });
Building.prototype.__defineSetter__('cardNextRecruit4Time', function(val) { this.args[8] = val; this.updateList[8] = 1; });
Building.prototype.__defineSetter__('barrackFormation1', function(val) { this.args[9] = val; this.updateList[9] = 1; });
Building.prototype.__defineSetter__('barrackFormation2', function(val) { this.args[10] = val; this.updateList[10] = 1; });
Building.prototype.__defineSetter__('barrackFormation3', function(val) { this.args[11] = val; this.updateList[11] = 1; });
Building.prototype.__defineSetter__('barrackActiveFormationId', function(val) { this.args[12] = val; this.updateList[12] = 1; });

global.Building = Building;