/* This file is generated by deploy.js automatically */
var BuildingModel = function BuildingModel() {
    this.type = 'hash';
    this.objectName = 'Building';
    this.abb = 'b';
    this.pk = 'userId';
    this.updateFilter = [0];
};

BuildingModel.prototype = new IModel();
BuildingModel.prototype.constructor = BuildingModel;

global.BuildingModel = new BuildingModel();
