/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var CardList = function CardList(pk, list) {
    this.init.call(this, pk, list);
};

CardList.prototype = new CardListBase();
CardList.prototype.constructor = CardList;
exports.CardList = CardList;