/* This file is generated by deploy.js automatically */
var CardListModel = function CardListModel() {
    this.type = 'list';
    this.objectName = 'CardList';
    this.abb = 'cl';
    this.child = 'Card';
    this.childModel = CardModel;
};

CardListModel.prototype = new IModel();
CardListModel.prototype.constructor = CardListModel;

global.CardListModel = new CardListModel();
