/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var CardModel = function CardModel() {
};

CardModel.prototype = new CardModelBase();
CardModel.prototype.constructor = CardModel;
exports.CardModel = new CardModel();