/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var CardListModel = function CardListModel() {
};

CardListModel.prototype = new CardListModelBase();
CardListModel.prototype.constructor = CardListModel;
exports.CardListModel = new CardListModel();