/* This file is generated by IFramework - Maker.js for user to rewrite Model file*/
var CardListModel = function CardListModel(args) {
};

CardListModel.prototype = new CardListModelBase();
CardListModel.prototype.constructor = CardListModel;
exports.CardListModel = CardListModel;