/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var Card = function Card(args) {
    this.init.call(this, args);
};

Card.prototype = new CardBase();
Card.prototype.constructor = Card;
exports.Card = Card;