/* This file is generated by deploy.js automatically */
var Card = function Card(args) {
    this.pk = 'cardId';
    this.column = ["cardId","cardTypeId","level","exp","strengthenLevel","strengthenExp","hp","atk","def","hit","dodge","critical","tough","initAnger","quality","flag","status","todoStatus","gemSlot"];
    this.abb = {"cardId":"ci","cardTypeId":"cti","level":"l","exp":"e","strengthenLevel":"sl","strengthenExp":"se","quality":"q","gemSlot":"gs"};
    this.init.call(this, args);
};

Card.prototype = new IObject();
Card.prototype.constructor = Card;

/* Getter */
Card.prototype.__defineGetter__('cardId', function() { return this.args[0]; });
Card.prototype.__defineGetter__('cardTypeId', function() { return this.args[1]; });
Card.prototype.__defineGetter__('level', function() { return this.args[2]; });
Card.prototype.__defineGetter__('exp', function() { return this.args[3]; });
Card.prototype.__defineGetter__('strengthenLevel', function() { return this.args[4]; });
Card.prototype.__defineGetter__('strengthenExp', function() { return this.args[5]; });
Card.prototype.__defineGetter__('hp', function() { return this.args[6]; });
Card.prototype.__defineGetter__('atk', function() { return this.args[7]; });
Card.prototype.__defineGetter__('def', function() { return this.args[8]; });
Card.prototype.__defineGetter__('hit', function() { return this.args[9]; });
Card.prototype.__defineGetter__('dodge', function() { return this.args[10]; });
Card.prototype.__defineGetter__('critical', function() { return this.args[11]; });
Card.prototype.__defineGetter__('tough', function() { return this.args[12]; });
Card.prototype.__defineGetter__('initAnger', function() { return this.args[13]; });
Card.prototype.__defineGetter__('quality', function() { return this.args[14]; });
Card.prototype.__defineGetter__('flag', function() { return this.args[15]; });
Card.prototype.__defineGetter__('status', function() { return this.args[16]; });
Card.prototype.__defineGetter__('todoStatus', function() { return this.args[17]; });
Card.prototype.__defineGetter__('gemSlot', function() { return this.args[18]; });

/* Setter */
Card.prototype.__defineSetter__('cardId', function(val) { this.args[0] = val; this.updateList[0] = 1; });
Card.prototype.__defineSetter__('cardTypeId', function(val) { this.args[1] = val; this.updateList[1] = 1; });
Card.prototype.__defineSetter__('level', function(val) { this.args[2] = val; this.updateList[2] = 1; });
Card.prototype.__defineSetter__('exp', function(val) { this.args[3] = val; this.updateList[3] = 1; });
Card.prototype.__defineSetter__('strengthenLevel', function(val) { this.args[4] = val; this.updateList[4] = 1; });
Card.prototype.__defineSetter__('strengthenExp', function(val) { this.args[5] = val; this.updateList[5] = 1; });
Card.prototype.__defineSetter__('hp', function(val) { this.args[6] = val; this.updateList[6] = 1; });
Card.prototype.__defineSetter__('atk', function(val) { this.args[7] = val; this.updateList[7] = 1; });
Card.prototype.__defineSetter__('def', function(val) { this.args[8] = val; this.updateList[8] = 1; });
Card.prototype.__defineSetter__('hit', function(val) { this.args[9] = val; this.updateList[9] = 1; });
Card.prototype.__defineSetter__('dodge', function(val) { this.args[10] = val; this.updateList[10] = 1; });
Card.prototype.__defineSetter__('critical', function(val) { this.args[11] = val; this.updateList[11] = 1; });
Card.prototype.__defineSetter__('tough', function(val) { this.args[12] = val; this.updateList[12] = 1; });
Card.prototype.__defineSetter__('initAnger', function(val) { this.args[13] = val; this.updateList[13] = 1; });
Card.prototype.__defineSetter__('quality', function(val) { this.args[14] = val; this.updateList[14] = 1; });
Card.prototype.__defineSetter__('flag', function(val) { this.args[15] = val; this.updateList[15] = 1; });
Card.prototype.__defineSetter__('status', function(val) { this.args[16] = val; this.updateList[16] = 1; });
Card.prototype.__defineSetter__('todoStatus', function(val) { this.args[17] = val; this.updateList[17] = 1; });
Card.prototype.__defineSetter__('gemSlot', function(val) { this.args[18] = val; this.updateList[18] = 1; });

global.Card = Card;