/* This file is generated by deploy.js automatically */
var ItemListModel = function ItemListModel() {
    this.type = 'list';
    this.objectName = 'ItemList';
    this.abb = 'il';
    this.child = 'Item';
    this.childModel = ItemModel;
};

ItemListModel.prototype = new IModel();
ItemListModel.prototype.constructor = ItemListModel;

global.ItemListModel = new ItemListModel();
