/* This file is generated by deploy.js automatically */
var ItemModel = function ItemModel() {
    this.type = 'hash';
    this.objectName = 'Item';
    this.abb = 'i';
    this.pk = 'itemId';
    this.pkAutoIncrement = true;
    this.updateFilter = [0];
};

ItemModel.prototype = new IModel();
ItemModel.prototype.constructor = ItemModel;

global.ItemModel = new ItemModel();
