/* This file is generated by deploy.js automatically */
var ItemList = function ItemList(pk, list) {
    IList.call(this, pk, list);
};

ItemList.prototype = new IList();
ItemList.prototype.constructor = ItemList;

global.ItemList = ItemList;