/* This file is generated by deploy.js automatically */
var User = function User(args) {
    this.pk = 'userId';
    this.column = ['userId', 'level', 'exp', 'money', 'energy', 'energyLimit', 'lastEnergyChargedTime', 'lastLoginTime', 'honor', 'dailyVisitedFriends', 'lastResetDailyVisitedFriendsTime', 'side', 'kingHeartLevel', 'kingHeartAppearance', 'loginCount'];
    this.init.call(this, args);
};

User.prototype = new IObject();
User.prototype.constructor = User;

/* Getter */
User.prototype.__defineGetter__('userId', function() { return this.args[0]; });
User.prototype.__defineGetter__('level', function() { return this.args[1]; });
User.prototype.__defineGetter__('exp', function() { return this.args[2]; });
User.prototype.__defineGetter__('money', function() { return this.args[3]; });
User.prototype.__defineGetter__('energy', function() { return this.args[4]; });
User.prototype.__defineGetter__('energyLimit', function() { return this.args[5]; });
User.prototype.__defineGetter__('lastEnergyChargedTime', function() { return this.args[6]; });
User.prototype.__defineGetter__('lastLoginTime', function() { return this.args[7]; });
User.prototype.__defineGetter__('honor', function() { return this.args[8]; });
User.prototype.__defineGetter__('dailyVisitedFriends', function() { return this.args[9]; });
User.prototype.__defineGetter__('lastResetDailyVisitedFriendsTime', function() { return this.args[10]; });
User.prototype.__defineGetter__('side', function() { return this.args[11]; });
User.prototype.__defineGetter__('kingHeartLevel', function() { return this.args[12]; });
User.prototype.__defineGetter__('kingHeartAppearance', function() { return this.args[13]; });
User.prototype.__defineGetter__('loginCount', function() { return this.args[14]; });

/* Setter */
User.prototype.__defineSetter__('userId', function(val) { this.args[0] = val; this.updateList[0] = 1; });
User.prototype.__defineSetter__('level', function(val) { this.args[1] = val; this.updateList[1] = 1; });
User.prototype.__defineSetter__('exp', function(val) { this.args[2] = val; this.updateList[2] = 1; });
User.prototype.__defineSetter__('money', function(val) { this.args[3] = val; this.updateList[3] = 1; });
User.prototype.__defineSetter__('energy', function(val) { this.args[4] = val; this.updateList[4] = 1; });
User.prototype.__defineSetter__('energyLimit', function(val) { this.args[5] = val; this.updateList[5] = 1; });
User.prototype.__defineSetter__('lastEnergyChargedTime', function(val) { this.args[6] = val; this.updateList[6] = 1; });
User.prototype.__defineSetter__('lastLoginTime', function(val) { this.args[7] = val; this.updateList[7] = 1; });
User.prototype.__defineSetter__('honor', function(val) { this.args[8] = val; this.updateList[8] = 1; });
User.prototype.__defineSetter__('dailyVisitedFriends', function(val) { this.args[9] = val; this.updateList[9] = 1; });
User.prototype.__defineSetter__('lastResetDailyVisitedFriendsTime', function(val) { this.args[10] = val; this.updateList[10] = 1; });
User.prototype.__defineSetter__('side', function(val) { this.args[11] = val; this.updateList[11] = 1; });
User.prototype.__defineSetter__('kingHeartLevel', function(val) { this.args[12] = val; this.updateList[12] = 1; });
User.prototype.__defineSetter__('kingHeartAppearance', function(val) { this.args[13] = val; this.updateList[13] = 1; });
User.prototype.__defineSetter__('loginCount', function(val) { this.args[14] = val; this.updateList[14] = 1; });

/* To Client */global.User = User;