/* This file is generated by deploy.js automatically */
var UserModel = function UserModel() {
    this.type = 'hash';
    this.objectName = 'User';
    this.abb = 'u';
    this.pk = 'userId';
    this.pkAutoIncrement = true;
    this.updateFilter = [0];
};

UserModel.prototype = new IModel();
UserModel.prototype.constructor = UserModel;

global.UserModel = new UserModel();
