/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var User = function User(args) {
    this.init.call(this, args);
};

User.prototype = new UserBase();
User.prototype.constructor = User;
exports.User = User;