/* This file is generated by IFramework - Maker.js for user to rewrite Model file*/
var UserModel = function UserModel(args) {
};

UserModel.prototype = new UserModelBase();
UserModel.prototype.constructor = UserModel;
exports.UserModel = UserModel;