/* This file is generated by deploy.js automatically */
var User = function User(args) {
    this.pk = 'id';
    this.column = ['id', 'level', 'exp', 'money', 'token', 'lastLoginTime'];
    this.init.call(this, args);
};

User.prototype = new IObject();
User.prototype.constructor = User;

/* Getter */
User.prototype.__defineGetter__('id', function() { return this.args[0]; });
User.prototype.__defineGetter__('level', function() { return this.args[1]; });
User.prototype.__defineGetter__('exp', function() { return this.args[2]; });
User.prototype.__defineGetter__('money', function() { return this.args[3]; });
User.prototype.__defineGetter__('token', function() { return this.args[4]; });
User.prototype.__defineGetter__('lastLoginTime', function() { return this.args[5]; });

/* Setter */
User.prototype.__defineSetter__('id', function(val) { this.args[0] = val; this.updateList[0] = 1; });
User.prototype.__defineSetter__('level', function(val) { this.args[1] = val; this.updateList[1] = 1; });
User.prototype.__defineSetter__('exp', function(val) { this.args[2] = val; this.updateList[2] = 1; });
User.prototype.__defineSetter__('money', function(val) { this.args[3] = val; this.updateList[3] = 1; });
User.prototype.__defineSetter__('token', function(val) { this.args[4] = val; this.updateList[4] = 1; });
User.prototype.__defineSetter__('lastLoginTime', function(val) { this.args[5] = val; this.updateList[5] = 1; });

global.User = User;