/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var UserModel = function UserModel() {
};

UserModel.prototype = new UserModelBase();
UserModel.prototype.constructor = UserModel;
exports.UserModel = new UserModel();