/* This file is generated by IFramework - Maker.js for user to rewrite List file */
!function () {
    var ConnectionList = function ConnectionList(pk, list) {
        this.init.call(this, pk, list);
    };

    ConnectionList.prototype = new I.Models.ConnectionListBase();
    ConnectionList.prototype.constructor = ConnectionList;

    I.Util.require('ConnectionList', 'Models', ConnectionList);
}();