/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
!function () {
    var Connection = function Connection(args) {
        this.init.call(this, args);
    };

    Connection.prototype = new I.Models.ConnectionBase();
    Connection.prototype.constructor = Connection;

    I.Util.require('Connection', 'Models', Connection);
}();