/* This file is generated by IFramework - Maker.js for user to rewrite ModelStore file */
!function () {
    var ConnectionStore = function ConnectionStore(db) {
    this.db = db;
    };

    ConnectionStore.prototype = new I.Models.ConnectionStoreBase();
    ConnectionStore.prototype.constructor = ConnectionStore;

    I.Util.require('ConnectionStore', 'Models', new ConnectionStore(db));
}();