/* This file is generated by deploy.js automatically */
var redis = require('redis');
global.db = redis.createClient();

/* IFramework */
require('./IConst.js');
require('./IException.js');
require('./IUtil.js');
require('./IObject.js');
require('./IList.js');
require('./IModel.js');
require('./IController.js');

/* App */
require('../model/User.js');
require('../model/UserModel.js');
require('../model/Item.js');
require('../model/ItemModel.js');
require('../model/ItemList.js');
require('../model/ItemListModel.js');
