var PvzkConst = {
    // card market
    'CARD_MARKET_RECRUIT_NORMAL_REFRESH_TYPE_ID': 1,
    'CARD_MARKET_RECRUIT_SILVER_REFRESH_TYPE_ID': 2,
    'CARD_MARKET_RECRUIT_GOLD_REFRESH_TYPE_ID': 3,
    'CARD_MARKET_RECRUIT_PLATINUM_REFRESH_TYPE_ID': 4,

    'CARD_MARKET_RECRUIT_NOT_USE_ITEM': 0,
    'CARD_MARKET_RECRUIT_USE_NORMAL_ITEM': 100,
    'CARD_MARKET_RECRUIT_USE_SILVER_ITEM': 101,
    'CARD_MARKET_RECRUIT_USE_GOLD_ITEM': 102,
    'CARD_MARKET_RECRUIT_USE_PLATINUM_ITEM': 103,

    // card status
    'CARD_STATUS_CANDIDATE': 0,
    'CARD_STATUS_IN_POCKET': 1,
};

global.PvzkConst = PvzkConst;
