/* This file is generated by IFramework - Maker.js for user to rewrite PK file */
I.Loader.ModelQueue.push(function() {
    var ConnectionPK = function ConnectionPK(pk) {
        this.init.call(this, pk);
    };

    ConnectionPK.prototype = new I.Models.ConnectionPKBase();
    var functions = {
        constructor: ConnectionPK,
    }
    I.Util.define(ConnectionPK.prototype, functions);
    I.Util.require('ConnectionPK', 'Models', ConnectionPK);
});