/* This file is generated by IFramework - Maker.js for user to rewrite PKStore file */
I.Loader.IndexedDBQueue.push(function (db) {
    var ConnectionPKStore = function ConnectionPKStore(db) {
        this.db = db;
    };

    ConnectionPKStore.prototype = new I.Models.ConnectionPKStoreBase();
    var functions = {
        constructor: ConnectionPKStore,
    }
    I.Util.define(ConnectionPKStore.prototype, functions);
    I.Util.require('ConnectionPKStore', 'Models', new ConnectionPKStore(db));
});