/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
I.Loader.ModelQueue.push(function () {
    var Connection = function Connection(args) {
        this.init.call(this, args);
    };

    Connection.prototype = new I.Models.ConnectionBase();
    var functions = {
        constructor: Connection,
    }
    I.Util.define(Connection.prototype, functions);
    I.Util.require('Connection', 'Models', Connection);
});