/* This file is generated by IFramework - Maker.js for user to rewrite PK file */
!function () {
    var ConnectionPK = function ConnectionPK(pk) {
        this.init.call(this, pk);
    };

    ConnectionPK.prototype = new I.Models.ConnectionPKBase();
    ConnectionPK.prototype.constructor = ConnectionPK;

    I.Util.require('ConnectionPK', 'Models', ConnectionPK);
}();