/* This file is generated by IFramework - Maker.js for user to rewrite ModelStore file */
I.Loader.IndexedDBQueue.push(function (db) {
    var ConnectionStore = function ConnectionStore(db) {
        this.db = db;
    };

    ConnectionStore.prototype = new I.Models.ConnectionStoreBase();
    var functions = {
        constructor: ConnectionStore,
    }
    I.Util.define(ConnectionStore.prototype, functions);
    I.Util.require('ConnectionStore', 'Models', new ConnectionStore(db));
});