/* This file is generated by IFramework - Maker.js for user to rewrite ListStore file */
I.Loader.IndexedDBQueue.push(function (db) {
    var ConnectionListStore = function ConnectionListStore(db) {
        this.db = db;
    };

    ConnectionListStore.prototype = new I.Models.ConnectionListStoreBase();
    var functions = {
        constructor: ConnectionListStore,
    }
    I.Util.define(ConnectionListStore.prototype, functions);
    I.Util.require('ConnectionListStore', 'Models', new ConnectionListStore(db));
});